// Generated by CoffeeScript 1.7.1
(function() {
  window.UnpClientInit = (function() {
    function UnpClientInit() {
      var _queryServer;
      _queryServer = UnpUtils.getQueryStringParam('server');
      if (_queryServer === null) {
        console.log(document.location.href);
        console.log(document.location.hostname);
        window.ServerUrl = 'ws://' + document.location.hostname + ':8080';
      } else {
        window.ServerUrl = 'ws://' + _queryServer;
      }
      new UnpInit();
      new UnpAuth($('#unpauth-div')[0]);
      new UnpChat($('#unpchat-div')[0]);
      new UnpMoveIt($('#unpmoveit-div')[0]);
      new UnpToolbar($('#unptoolbar-div')[0], [
        {
          'text': 'visual fx',
          'menu': [
            {
              'text': 'stripe array',
              'click': function() {
                var _cFx, _confObj;
                _confObj = {};
                _confObj.startX = 100;
                _confObj.startY = 100;
                _confObj.endX = 0;
                _confObj.endY = 0;
                _confObj.color1 = 'rgba(120, 120, 120, 0.7)';
                _confObj.color2 = 'rgba(200, 200, 200, 0.5)';
                _confObj.stripeWidth = 60;
                _confObj.stripeNum = 5;
                _cFx = new UnpVisualFx.StripeArray($('#unpmoveit-div canvas')[0]);
                _cFx.Config(_confObj);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'bezier array',
              'click': function() {
                var _cFx, _confObj;
                _confObj = {};
                _confObj.startX = 0;
                _confObj.startY = 0;
                _confObj.endX = 0;
                _confObj.endY = 0;
                _confObj.colorFrom = new UnpColor(180, 0, 100, 0.5);
                _confObj.colorTo = new UnpColor(0, 0, 180, 0.5);
                _confObj.lineWidth = 3;
                _confObj.lineNum = 7;
                _cFx = new UnpVisualFx.BezierArray($('#unpmoveit-div canvas')[0]);
                _cFx.Config(_confObj);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'line array',
              'click': function() {
                var _cFx, _confObj;
                _confObj = {};
                _confObj.startX = 0;
                _confObj.startY = 0;
                _confObj.endX = 0;
                _confObj.endY = 0;
                _confObj.colorFrom = new UnpColor(0, 0, 220, 0.5);
                _confObj.colorTo = new UnpColor(220, 220, 250, 0.5);
                _confObj.lineWidth = 1;
                _confObj.lineNum = 7;
                _cFx = new UnpVisualFx.LineArray($('#unpmoveit-div canvas')[0]);
                _cFx.Config(_confObj);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'timed bezier',
              'click': function() {
                var _cFx, _confObj;
                _confObj = {};
                _confObj.startX = 0;
                _confObj.startY = 0;
                _confObj.endX = 0;
                _confObj.endY = 0;
                _confObj.lineColor = new UnpColor(180, 0, 100, 0.5);
                _confObj.lineWidth = 3;
                _confObj.maxDist = 25;
                _cFx = new UnpVisualFx.TimedBezier($('#unpmoveit-div canvas')[0]);
                _cFx.Config(_confObj);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'timed bezier array',
              'click': function() {
                var i, _cFx, _confObj, _fxArray, _i;
                _fxArray = [];
                for (i = _i = 0; _i <= 9; i = ++_i) {
                  _confObj = {};
                  _confObj.startX = 0;
                  _confObj.startY = 0;
                  _confObj.endX = 0;
                  _confObj.endY = 0;
                  _confObj.lineColor = new UnpColor(0, 180, 50, 0.3);
                  _confObj.lineWidth = 1 + (i % 3);
                  _confObj.maxDist = 10;
                  _cFx = new UnpVisualFx.TimedBezier($('#unpmoveit-div canvas')[0]);
                  _cFx.Config(_confObj);
                  _fxArray.push(_cFx);
                }
                return window._testVisualFx = _fxArray;
              }
            }, {
              'text': 'timed bezier array (big)',
              'click': function() {
                var i, _cFx, _confObj, _fxArray, _i;
                _fxArray = [];
                for (i = _i = 0; _i <= 9; i = ++_i) {
                  _confObj = {};
                  _confObj.startX = 0;
                  _confObj.startY = 0;
                  _confObj.endX = 0;
                  _confObj.endY = 0;
                  _confObj.lineColor = new UnpColor(100, 0, 0, 0.3);
                  _confObj.lineWidth = 3 + (i % 3);
                  _confObj.maxDist = 200;
                  _cFx = new UnpVisualFx.TimedBezier($('#unpmoveit-div canvas')[0]);
                  _cFx.Config(_confObj);
                  _fxArray.push(_cFx);
                }
                return window._testVisualFx = _fxArray;
              }
            }
          ]
        }, {
          'text': 'particle fx',
          'menu': [
            {
              'text': 'explosion',
              'click': function() {
                var _cFx;
                _cFx = new UnpVisualFx.Explosion($('#unpmoveit-div canvas')[0]);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'flame',
              'click': function() {
                var _cFx;
                _cFx = new UnpVisualFx.Flame($('#unpmoveit-div canvas')[0]);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'swirl',
              'click': function() {
                var _cFx;
                _cFx = new UnpVisualFx.Swirl($('#unpmoveit-div canvas')[0]);
                return window._testVisualFx = _cFx;
              }
            }, {
              'text': 'spiral',
              'click': function() {
                var _cFx;
                _cFx = new UnpVisualFx.Spiral($('#unpmoveit-div canvas')[0]);
                return window._testVisualFx = _cFx;
              }
            }
          ]
        }
      ]);
    }

    return UnpClientInit;

  })();

}).call(this);

//# sourceMappingURL=unpclient.map
