// Generated by CoffeeScript 1.7.1
(function() {
  window.UnpColor = (function() {
    function UnpColor(Red, Green, Blue, Alpha) {
      this.Red = Red;
      this.Green = Green;
      this.Blue = Blue;
      this.Alpha = Alpha;
    }

    UnpColor.prototype.getValue = function() {
      return 'rgba(' + this.Red + ',' + this.Green + ',' + this.Blue + ',' + this.Alpha + ')';
    };

    return UnpColor;

  })();

}).call(this);

//# sourceMappingURL=unpgraphics.map
