// Generated by CoffeeScript 1.7.1
(function() {
  window.UnpToolbar = (function() {
    UnpToolbar._UnpToolbarOpen = function(targetElement) {
      $(targetElement).parent().find('.unptoolbar-button-menu-open').removeClass('unptoolbar-button-menu-open');
      return $(targetElement).addClass('unptoolbar-button-menu-open');
    };

    UnpToolbar._UnpToolbarClose = function(targetElement) {
      return $(targetElement).removeClass('unptoolbar-button-menu-open');
    };

    UnpToolbar._UnpToolbarToggle = function(targetElement) {
      if ($(targetElement).hasClass('unptoolbar-button-menu-open') === true) {
        return this._UnpToolbarClose(targetElement);
      } else {
        return this._UnpToolbarOpen(targetElement);
      }
    };

    function UnpToolbar(htmlCont, menuData) {
      var _contDiv, _isWellOutTimer;
      console.log;
      _contDiv = document.createElement('div');
      $(_contDiv).addClass('unptoolbar-cont').addClass('unptoolbar-cont-closed');
      _isWellOutTimer = null;
      $(_contDiv).on('mouseover', function() {
        $(_contDiv).removeClass('unptoolbar-cont-closed');
        if (_isWellOutTimer) {
          window.clearTimeout(_isWellOutTimer);
          return _isWellOutTimer = null;
        }
      });
      $(_contDiv).bind('mouseout', function() {
        var callback;
        if (_isWellOutTimer !== null) {
          window.clearTimeout(_isWellOutTimer);
        }
        callback = function() {
          console.log;
          return $(_contDiv).addClass('unptoolbar-cont-closed');
        };
        return _isWellOutTimer = window.setTimeout(callback, 500);
      });
      $(menuData).each(function() {
        var _cButton, _cMenuCont;
        console.log;
        _cButton = document.createElement('div');
        $(_cButton).addClass('unptoolbar-button').html('<span class="unptoolbar-button-text">' + this.text + '</span>');
        if (this.click) {
          $(_cButton).bind('click', this.click);
        }
        if (this.menu) {
          _cMenuCont = document.createElement('div');
          $(_cMenuCont).addClass('unptoolbar-button-menu');
          $(this.menu).each(function() {
            var _cMenuElement;
            _cMenuElement = document.createElement('div');
            $(_cMenuElement).html('<span>' + this.text + '</span>');
            $(_cMenuElement).addClass('unptoolbar-button-menu-element');
            if (this.click) {
              $(_cMenuElement).bind('click', this.click);
            }
            return $(_cMenuCont).append(_cMenuElement);
          });
          $(_cButton).bind('mouseover', function() {
            return UnpToolbar._UnpToolbarOpen(this);
          });
          $(_cButton).bind('mouseout', function() {
            return UnpToolbar._UnpToolbarClose(this);
          });
          $(_cButton).append(_cMenuCont);
        }
        return $(_contDiv).append(_cButton);
      });
      $(htmlCont).append(_contDiv);
    }

    return UnpToolbar;

  })();

}).call(this);

//# sourceMappingURL=unpmenu.map
