// Generated by CoffeeScript 1.7.1
(function() {
  UnpUtils._LoadingSplashCount = 0;

  window.UnpWarning = (function() {
    function UnpWarning() {}

    UnpWarning.constructor = function() {};

    UnpWarning.WarningSet = function(warningText, buttonData) {
      var _buttonDiv;
      console.log;
      $('#unp-warning-text').html(warningText);
      $('#unp-warning-splash').show();
      _buttonDiv = $('#unp-warning-buttons').first();
      $(_buttonDiv).html('');
      $(buttonData).each(function() {
        var _cButton, _clickFunction;
        console.log;
        _cButton = document.createElement('div');
        _clickFunction = this.click;
        return $(_cButton).addClass('unp-warning-button').html(this.text).bind('click', function() {
          UnpWarning.WarningHide();
          if (_clickFunction !== null) {
            return _clickFunction;
          }
        });
      });
      return UnpWarning.WarningShow();
    };

    UnpWarning.Alert = function(alertText, onButtonOk) {
      var buttonData;
      console.log;
      buttonData = [
        {
          'text': 'OK',
          'click': onButtonOk
        }
      ];
      return UnpWarning.WarningSet(alertText, buttonData);
    };

    UnpWarning.Confirm = function(confirmText, onButtonOk, onButtonCancel) {
      console.log;
      return UnpWarning.WarningSet(confirmText, [
        {
          'text': 'OK',
          'click': onButtonOk
        }, {
          'text': 'Cancel',
          'click': onButtonCancel
        }
      ]);
    };

    UnpWarning.WarningShow = function() {
      console.log;
      return $('#unp-warning-splash').show;
    };

    UnpWarning.WarningHide = function() {
      console.log;
      return $('#unp-warning-splash').hide;
    };

    UnpWarning.LoadingSplashShow = function() {
      console.log;
      UnpUtils._LoadingSplashCount++;
      if (UnpUtils._LoadingSplashCount > 0) {
        return $('#unp-loading-splash').show();
      }
    };

    UnpWarning.LoadingSplashHide = function() {
      console.log;
      UnpUtils._LoadingSplashCount--;
      if (UnpUtils._LoadingSplashCount <= 0) {
        UnpUtils._LoadingSplashCount = 0;
        return $('#unp-loading-splash').hide();
      }
    };

    return UnpWarning;

  })();

}).call(this);

//# sourceMappingURL=unpwarning.map
