// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.UnpAuth = (function(_super) {
    __extends(UnpAuth, _super);

    function UnpAuth(htmlCont) {
      var self;
      UnpAuth.__super__.constructor.call(this, 'unpauth');
      this.authDisplay = document.createElement('div');
      self = this;
      $(this.authDisplay).addClass('unpauth-cont').html('<div class="unpauth-login-desc">Login</div>' + '<div class="unpauth-login-input"><input type="text"/></div>' + '<div class="unpauth-logout">Logout</div>');
      $(this.authDisplay).find('.unpauth-login-input input').bind('keyup', function(evtObj) {
        if (evtObj.keyCode === 13) {
          console.log(this.value);
          self.authLogin(this.value);
          return $(this).val('');
        }
      });
      $(this.authDisplay).find('.unpauth-logout').bind('click', function(evtObj) {
        console.log;
        return self.authLogout(this.value);
      });
      $(htmlCont).append(this.authDisplay);
    }

    UnpAuth.prototype.handleAction = function(actionName, actionData) {
      console.log;
      switch (actionName) {
        case 'login-result':
          UnpWarning.LoadingSplashHide();
          if (actionData['status'] === 'ok') {
            return $(this.authDisplay).parent().addClass('unpauth-login-ok');
          }
          break;
        case 'logout-result':
          UnpWarning.LoadingSplashHide();
          if (actionData['status'] === 'ok') {
            return document.location.reload();
          }
      }
    };

    UnpAuth.prototype.authLogin = function(textVal) {
      var _umpMsg;
      console.log;
      UnpWarning.LoadingSplashShow();
      _umpMsg = new UnpMessage();
      _umpMsg.addAction(this.modName, 'login', {
        'username': textVal
      });
      return _umpMsg.send();
    };

    UnpAuth.prototype.authLogout = function(textVal) {
      var _umpMsg;
      console.log;
      UnpWarning.LoadingSplashShow();
      _umpMsg = new UnpMessage();
      _umpMsg.addAction(this.modName, 'logout', {});
      return _umpMsg.send();
    };

    return UnpAuth;

  })(window.UnpModule);

}).call(this);

//# sourceMappingURL=auth.map
