// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.UnpChat = (function(_super) {
    __extends(UnpChat, _super);

    function UnpChat(htmlCont) {
      var self;
      console.log;
      UnpChat.__super__.constructor.call(this, 'unpchat');
      self = this;
      this.chatDisplay = document.createElement('div');
      $(this.chatDisplay).addClass('unpchat-cont').html('<div class="unpchat-message-log"></div>' + '<div class="unpchat-message-input"><input type="text"/></div>');
      $(this.chatDisplay).find('.unpchat-message-input input').bind('keyup', function(evtObj) {
        console.log;
        if (evtObj.keyCode === 13) {
          console.log;
          self.chatInput(this.value);
          return $(this).val('');
        }
      });
      $(htmlCont).append(this.chatDisplay);
      this.handleAction = function(actionName, actionData) {
        var _cMsgElem, _msgColor, _msgLog;
        console.log;
        switch (actionName) {
          case 'message':
            _msgLog = $(this.chatDisplay).find('.unpchat-message-log')[0];
            _cMsgElem = document.createElement('div');
            _msgColor = actionData.color;
            $(_cMsgElem).addClass('unpchat-message').css('color', _msgColor).html('<div class="unpchat-from">' + actionData.from + '</div>' + '<div class="unpchat-to">' + actionData.to + '</div>' + '<div class="unpchat-text">' + actionData.text + '</div>');
            $(_msgLog).append(_cMsgElem);
            return _msgLog.scrollTop = _msgLog.scrollHeight;
          case 'sysmsg':
            _msgLog = $(this.chatDisplay).find('.unpchat-message-log')[0];
            _cMsgElem = document.createElement('div');
            _msgColor = actionData.color;
            $(_cMsgElem).addClass('unpchat-message').css('color', _msgColor).addClass('unpchat-sysmsg').html('<div class="unpchat-text">' + actionData.text + '</div>' + '</div>');
            $(_msgLog).append(_cMsgElem);
            return _msgLog.scrollTop = _msgLog.scrollHeight;
        }
      };
      this.chatInput = function(textVal) {
        var _umpMsg;
        console.log;
        _umpMsg = new UnpMessage();
        _umpMsg.addAction(this.modName, 'message', {
          'to': 'all',
          'text': textVal
        });
        return _umpMsg.send();
      };
    }

    return UnpChat;

  })(window.UnpModule);

}).call(this);

//# sourceMappingURL=chat.map
